<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BlazorApp_Tutorial</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net6.0\BlazorApp Tutorial.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net6.0\BlazorApp Tutorial.GlobalUsings.g.cs" />
    <Compile Include="obj\Debug\net6.0\BlazorApp Tutorial.RazorAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net6.0\appsettings.Development.json" />
    <Content Include="bin\Debug\net6.0\appsettings.json" />
    <Content Include="bin\Debug\net6.0\BlazorApp Tutorial.deps.json" />
    <Content Include="bin\Debug\net6.0\BlazorApp Tutorial.runtimeconfig.json" />
    <Content Include="bin\Debug\net6.0\BlazorApp Tutorial.staticwebassets.runtime.json" />
    <Content Include="obj\BlazorApp Tutorial.csproj.nuget.dgspec.json" />
    <Content Include="obj\Debug\net6.0\BlazorApp Tutorial.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net6.0\project.razor.vs.json" />
    <Content Include="obj\Debug\net6.0\scopedcss\bundle\BlazorApp Tutorial.styles.css" />
    <Content Include="obj\Debug\net6.0\scopedcss\projectbundle\BlazorApp Tutorial.bundle.scp.css" />
    <Content Include="obj\Debug\net6.0\scopedcss\Shared\MainLayout.razor.rz.scp.css" />
    <Content Include="obj\Debug\net6.0\scopedcss\Shared\NavMenu.razor.rz.scp.css" />
    <Content Include="obj\Debug\net6.0\staticwebassets.build.json" />
    <Content Include="obj\Debug\net6.0\staticwebassets.development.json" />
    <Content Include="obj\Debug\net6.0\staticwebassets.pack.json" />
    <Content Include="obj\project.assets.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net6.0\BlazorApp Tutorial.dll" />
    <None Include="bin\Debug\net6.0\BlazorApp Tutorial.exe" />
    <None Include="bin\Debug\net6.0\BlazorApp Tutorial.pdb" />
    <None Include="obj\BlazorApp Tutorial.csproj.nuget.g.props" />
    <None Include="obj\BlazorApp Tutorial.csproj.nuget.g.targets" />
    <None Include="obj\Debug\net6.0\apphost.exe" />
    <None Include="obj\Debug\net6.0\BlazorApp Tutorial.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net6.0\BlazorApp Tutorial.assets.cache" />
    <None Include="obj\Debug\net6.0\BlazorApp Tutorial.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net6.0\BlazorApp Tutorial.csproj.BuildWithSkipAnalyzers" />
    <None Include="obj\Debug\net6.0\BlazorApp Tutorial.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net6.0\BlazorApp Tutorial.dll" />
    <None Include="obj\Debug\net6.0\BlazorApp Tutorial.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net6.0\BlazorApp Tutorial.genruntimeconfig.cache" />
    <None Include="obj\Debug\net6.0\BlazorApp Tutorial.MvcApplicationPartsAssemblyInfo.cache" />
    <None Include="obj\Debug\net6.0\BlazorApp Tutorial.pdb" />
    <None Include="obj\Debug\net6.0\BlazorApp Tutorial.RazorAssemblyInfo.cache" />
    <None Include="obj\Debug\net6.0\refint\BlazorApp Tutorial.dll" />
    <None Include="obj\Debug\net6.0\ref\BlazorApp Tutorial.dll" />
    <None Include="obj\Debug\net6.0\staticwebassets\msbuild.BlazorApp Tutorial.Microsoft.AspNetCore.StaticWebAssets.props" />
    <None Include="obj\Debug\net6.0\staticwebassets\msbuild.build.BlazorApp Tutorial.props" />
    <None Include="obj\Debug\net6.0\staticwebassets\msbuild.buildMultiTargeting.BlazorApp Tutorial.props" />
    <None Include="obj\Debug\net6.0\staticwebassets\msbuild.buildTransitive.BlazorApp Tutorial.props" />
    <None Include="obj\project.nuget.cache" />
  </ItemGroup>

</Project>
